### ISSUE TITLE
Need requests, but missing from requirements

### ISSUE THREAD

**Issue by lahwran** [mila-udem/fuel#171]
I tried to run fuel-download in a virtual environment, but it gave me this error:

```
Traceback (most recent call last):
  File "/Users/lahwran/blocks/ve/bin/fuel-download", line 5, in <module>
    from fuel import downloaders
  File "/Users/lahwran/blocks/ve/lib/python2.7/site-packages/fuel/downloaders/__init__.py", line 9, in <module>
    from fuel.downloaders import binarized_mnist
  File "/Users/lahwran/blocks/ve/lib/python2.7/site-packages/fuel/downloaders/binarized_mnist.py", line 1, in <module>
    from fuel.downloaders.base import default_downloader
  File "/Users/lahwran/blocks/ve/lib/python2.7/site-packages/fuel/downloaders/base.py", line 5, in <module>
    import requests
ImportError: No module named requests
```

I checked requirements.txt and setup.py, neither mention requests. Probably would be good to add that.

**Comment by dwf** [comment]
Thanks for the report. I made a PR.

I think the reason Travis didn't catch this is that it's getting pulled in as a dependency of another package only required for running the tests, possibly mock.
