### ISSUE TITLE
fuel require which version of numpy?

### ISSUE THREAD

**Issue by DanlanChen** [mila-udem/fuel#328]
from fuel.datasets.dogs_vs_cats import DogsVsCats
RuntimeError: module compiled against API version a but this version of numpy is 9
WARNING (theano.tensor.blas): Failed to import scipy.linalg.blas, and Theano flag blas.ldflags is empty. Falling back on slower implementations for dot(matrix, vector), dot(vector, matrix) and dot(vector, vector) (numpy.core.multiarray failed to import)
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/datasets/__init__.py", line 2, in <module>
    from fuel.datasets.base import (Dataset, IterableDataset,
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/datasets/base.py", line 9, in <module>
    from fuel.streams import DataStream
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/streams.py", line 7, in <module>
    from fuel.server import recv_arrays
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/server.py", line 7, in <module>
    from fuel.utils import buffer_
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/fuel/utils/__init__.py", line 6, in <module>
    import h5py
  File "/home2/ift6ed05/anaconda2/lib/python2.7/site-packages/h5py/__init__.py", line 23, in <module>
    from . import _conv
  File "h5py/h5t.pxd", line 14, in init h5py._conv (/home/ilan/minonda/conda-bld/work/h5py/_conv.c:7364)
  File "h5py/numpy.pxd", line 66, in init h5py.h5t (/home/ilan/minonda/conda-bld/work/h5py/h5t.c:20460)
ValueError: numpy.dtype has the wrong size, try recompiling
>>>

**Comment by DanlanChen** [comment]
I am using 1.9.3 version

**Comment by DanlanChen** [comment]
hello, I have no issue after upgrading my numpy.You can close the issue now.
