### ISSUE TITLE
KeyError: "Unable to open object (Object 'image_features' doesn't exist)"

### ISSUE THREAD

**Issue by ch3njust1n** [mila-udem/fuel#375]
I followed the example (http://fuel.readthedocs.io/en/latest/h5py_dataset.html) and got this error.

Traceback (most recent call last):
  File "train.py", line 55, in <module>
    tr_data, te_data, tr_stream, val_stream, te_stream = faces(ntrain=ntrain)
  File "/home/sandbox/dcgan/faces/load.py", line 12, in faces
    tr_data = H5PYDataset('11230_128px.hdf5', which_sets=('train',))
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 188, in __init__
    self._parse_dataset_info()
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 228, in _parse_dataset_info
    self.vlen_sources = self.get_vlen_sources(handle)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 379, in get_vlen_sources
    source = h5file[source_name]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip-4rPeHA-build/h5py/h5o.c:3570)
KeyError: "Unable to open object (Object 'image_features' doesn't exist)"

**Comment by dmitriy-serdyuk** [comment]
I just run this example and it worked without any problems. Make sure that you follow all the steps. Try to ask the mail list list for help to put your data into h5py. If you still think that it is a bug in fuel, feel free to reopen, but please provide the minimal code to reproduce it and more information about your system.
