### ISSUE TITLE
pip install git+https://github.com/mila-udem/fuel.git@stable

### ISSUE THREAD

**Issue by weizier** [mila-udem/fuel#398]
When I use the command referred as the title of this issue, I met the error as follows:

Collecting git+https://github.com/mila-udem/fuel.git@stable
  Cloning https://github.com/mila-udem/fuel.git (to stable) to c:\users\weizie~1\appdata\local\temp\pip-27ojmbjj-build
Collecting numpy (from fuel==0.2.0)
  Using cached numpy-1.13.0-cp36-none-win_amd64.whl
Requirement already satisfied: six in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Collecting picklable_itertools (from fuel==0.2.0)
Requirement already satisfied: pyyaml in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Requirement already satisfied: h5py in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Requirement already satisfied: tables in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Collecting progressbar2 (from fuel==0.2.0)
  Using cached progressbar2-3.30.2-py2.py3-none-any.whl
Requirement already satisfied: pyzmq in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Requirement already satisfied: scipy in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Requirement already satisfied: pillow in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Requirement already satisfied: requests in f:\anaconda3\lib\site-packages (from fuel==0.2.0)
Requirement already satisfied: numexpr>=2.4 in f:\anaconda3\lib\site-packages (from tables->fuel==0.2.0)
Collecting python-utils>=2.1.0 (from progressbar2->fuel==0.2.0)
  Using cached python_utils-2.1.0-py2.py3-none-any.whl
Requirement already satisfied: olefile in f:\anaconda3\lib\site-packages (from pillow->fuel==0.2.0)
Installing collected packages: numpy, picklable-itertools, python-utils, progressbar2, fuel
  Running setup.py install for fuel ... error
Exception:
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "F:\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "F:\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "F:\Anaconda3\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "F:\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "F:\Anaconda3\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte

I've ever searched this error on Google, maybe it has been an issue of pip itself for a long time. But who could do me a favor? I'd appreciate it.

**Comment by charlesreid1** [comment]
Have you upgraded to the latest pip?

**Comment by dmitriy-serdyuk** [comment]
I don't think it will work on Windows. You may try to mitigate this problem removing all text from `README.rst`.
